remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme

title: [Open Language â€” LT Support]
description: ["Or: Can I use my language? Documentation of open language technology (LT) support in common OS's and Office packages. <br/> <br/> âš ï¸ This is early work, most is still TBW. Please contribute by forking and submitting PRs ğŸ˜Š"]
